
// get 
export const PROJECT_LOADING = 'PROJECT_LOADING';
export const PROJECT_SUCCESS = 'PROJECT_SUCCESS';
export const PROJECT_FAILURE = 'PROJECT_FAILURE';

// post


export const SAVE_PROJECT_LOADING = 'SAVE_PROJECT_LOADING';
export const SAVE_PROJECT_SUCCESS = 'SAVE_PROJECT_SUCCESS';
export const SAVE_PROJECT_FAILURE = 'SAVE_PROJECT_FAILURE';

